name: Generează întrebări BAC

on:
  workflow_dispatch:
    inputs:
      subiect:
        description: 'Subiect BAC'
        required: true
        default: 'Genul liric'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalează dependențe
        run: npm install openai

      - name: Rulează scriptul de generare
        run: node scripts/gen.js "${{ github.event.inputs.subiect }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit rezultat
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/intrebari.json
          git commit -m "Întrebări generate automat"
          git push
